apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: kube-sample
  labels:
    tw-app: kube-sample
    tw-team: transfer-experience
spec:
  minReplicas: 3
  maxReplicas: 30
  targetCPUUtilizationPercentage: 70
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: kube-sample
