version: 2
jobs:
  build:
    working_directory: ~/kube-sample
    docker:
      - image: ruby:2.3.3
    steps:
      - checkout
      - run:
          name: Instal all dependencies 
          command: gem install bundler 
      - persist_to_workspace:
          root: .
          paths:
            - '*'
  deployment:
    working_directory: ~/kube-sample
    docker:
      - image: twdev/k8s-deployer:1
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: ~/kube-sample
      - run:
          name: Push the docker image
          command: k8s-deployment docker-build docker-push
          environment:
            DEPLOY_DOCKERFILE: ./Dockerfile
            DEPLOY_IMAGE_NAME: kube-sample
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deployment:
          context: org-global
          requires:
            - build
          filters:
            branches:
              only:
                - master
